server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/accounttransaction?useSSL=false
    username: root
    password: 123456
#swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#配置mapper的映射文件的位置
mybatis:
  mapper-locations: classpath:/mapping/*.xml

